// Generated by CoffeeScript 1.6.3
(function() {
  var App, BlinkInOrderDemo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BlinkInOrderDemo = (function() {
    function BlinkInOrderDemo() {
      this.handleClick = __bind(this.handleClick, this);
      clearInterval();
      setWatch(this.handleClick, BTN, {
        repeat: true,
        edge: 'rising'
      });
    }

    BlinkInOrderDemo.prototype.useSeconds = 1000;

    BlinkInOrderDemo.prototype.currentLedsIndex = -1;

    BlinkInOrderDemo.prototype.leds = [];

    BlinkInOrderDemo.prototype.ledsKeys = [];

    BlinkInOrderDemo.prototype.handleClick = function() {
      var _ref;
      if (!this.ledsKeys.length) {
        this.ledsKeys = Object.keys(this.leds);
      }
      if (!this.ledsKeys.length) {
        return;
      }
      if (this.currentLedsIndex > -1) {
        this.leds[this.ledsKeys[this.currentLedsIndex]].write(0);
        this.currentLedsIndex++;
      }
      if ((_ref = this.currentLedsIndex) === this.ledsKeys.length || _ref === (-1)) {
        this.currentLedsIndex = 0;
      }
      return this.leds[this.ledsKeys[this.currentLedsIndex]].write(1);
    };

    return BlinkInOrderDemo;

  })();

  App = (function() {
    function App() {
      var demo;
      demo = new BlinkInOrderDemo();
      demo.leds = {
        LED1: LED1,
        LED3: LED3,
        LED5: LED5,
        LED7: LED7,
        LED8: LED8,
        LED6: LED6,
        LED4: LED4,
        LED2: LED2
      };
    }

    return App;

  })();

  new App();

}).call(this);
