// Generated by CoffeeScript 1.6.3
(function() {
  var App, BlinkAllLedsDemo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  BlinkAllLedsDemo = (function() {
    function BlinkAllLedsDemo() {
      this.main = __bind(this.main, this);
      clearInterval();
    }

    BlinkAllLedsDemo.prototype.useSeconds = 1000;

    BlinkAllLedsDemo.prototype.writeLedRandom = function(led, noWait) {
      var rand,
        _this = this;
      noWait = noWait ? 0 : 1;
      rand = this.random();
      return setTimeout(function() {
        var booleanSeed;
        booleanSeed = _this.random() > 0.8;
        led.write(booleanSeed);
        return _this.writeLedRandom(led);
      }, rand * this.useSeconds * noWait);
    };

    BlinkAllLedsDemo.prototype.random = function() {
      var randNums;
      randNums = Math.sin(getTime()).toString().substring(6);
      return parseFloat('0.' + randNums);
    };

    BlinkAllLedsDemo.prototype.main = function() {
      var key, led, _ref, _results;
      _ref = this.leds;
      _results = [];
      for (key in _ref) {
        led = _ref[key];
        led.write(0);
        _results.push(this.writeLedRandom(led, true));
      }
      return _results;
    };

    return BlinkAllLedsDemo;

  })();

  App = (function() {
    function App() {
      var demo;
      demo = new BlinkAllLedsDemo();
      demo.leds = {
        LED1: LED1,
        LED2: LED2,
        LED3: LED3,
        LED4: LED4,
        LED5: LED5,
        LED6: LED6,
        LED7: LED7,
        LED8: LED8
      };
      demo.main();
    }

    return App;

  })();

  new App();

}).call(this);
